### ISSUE TITLE
cant save.ora files

### ISSUE THREAD

**Issue by temginson** [PintaProject/Pinta#999] opened 2024-09-27 10:01 UTC
**Description**
when trying to save a .ora file it saves but when you try and open it again it opens, but you can't save

**To Reproduce**
After saving a file from .png to .ora, reopening it in Pinta, and making changes to the drawing, an error occurs when attempting to save the file again. and you get the following0 message Pinta is unable to save the file in the specified format.

**Additional Info**

**Version**
operating system windows10 and which version of Pinta (e.g. 2.1.2) you are using.

**Comment by cameronwhite** [comment] 2024-09-28 15:59
Is there a more detailed error message / stack trace that appears with the error?

It sounds vaguely similar to #584

**Comment by temginson** [comment] 2024-09-30 08:47
yep its the same as #584 and no more detailed error message other than 
![image](https://github.com/user-attachments/assets/d7bae127-1b14-40ec-9141-b0e33c1ae61f)
witch says Pinta does not support saving images in this file format

**Comment by cameronwhite** [comment] 2024-10-01 02:32
Could you try to reproduce this in the Pinta 2.2 development builds? (e.g. using the installer from https://github.com/PintaProject/Pinta/releases/tag/dev-preview-builds)

**Comment by cameronwhite** [comment] 2024-10-02 03:11
Thanks, that's good to know it's fixed in Pinta 2.2
I'd suggest submitting a separate bug report for the Wacom issue (if you can attach a video / screen grab explaining the issue that would be helpful since I don't have a tablet myself)

**Closed** 2024-10-02 07:10 UTC
Labels: bug
