### ISSUE TITLE
No darkmode in MacOS

### ISSUE THREAD

**Issue by jewtvet** [PintaProject/Pinta#1165] opened 2024-11-26 03:19 UTC
**Description**
No color theme switcher in MacOS version. System theme is dark

**To Reproduce**
1. Download Mac version from official site
2. Start it

**Version**
MacOS 15.1.1
Pinta 2.1.2

<img width="199" alt="image" src="https://github.com/user-attachments/assets/d08ce0c6-8ceb-4912-9f59-32f2058698fc">
<img width="374" alt="image" src="https://github.com/user-attachments/assets/c2cd9539-d4df-40b6-a4f9-6f2035db2da8">

**Comment by cameronwhite** [comment] 2024-11-27 03:19
Marking as a duplicate of #782 - the next major release of Pinta will automatically pick up the system's dark theme preference and has a toggle to explicitly switch

**Closed by cameronwhite** 2024-11-27 03:19 UTC
Labels: bug
